Repository open-ce/open-ce, pull requests merged in 2020-11, with the labels that each got.

#156 Fix python 3.8 environments
  conda_build_config.yaml
  envs/dali-env.yaml
  envs/pytorch-env.yaml
  envs/tensorrt-env.yaml
  envs/transformers-env.yaml
Labels: bug

#167 Make codecov comment better.
  codecov.yml
Labels: CI

#159 Doc updates
  README.md
  doc/README.build_env.md
  doc/README.build_image.md
Labels: documentation

#97 Adding Environment Yaml file README - first draft
  doc/README.yaml.md
Labels: documentation
