Repository open-ce/open-ce, pull requests merged in 2020-09, with the labels that each got.

#8 Add additional documentation to the Getting Started section
  README.md
Labels: documentation

#13 Add source style
  .github/workflows/builder-unit-test.yml
  .pylintrc
  builder/build_env.py
  builder/build_feedstock.py
  builder/util.py
  builder/utils.py
  tests/README.md
  tests/build_env_test.py
  tests/build_feedstock_test.py
  tests/util_test.py
Labels: enhancement

#14 update tqdm pin
  conda_build_config.yaml
  envs/pytorch-env.yaml
Labels: PyTorch, versioning

#18 Add functionality to build_env for building in docker containers
  README.md
  builder/build_env.py
  builder/docker_build.py
  ci_common_scripts/imageconfig
  doc/README.build_env.md
  images/builder/Dockerfile
  tests/build_env_test.py
  tests/docker_build_test.py
Labels: enhancement

#28 Handle import error.
  README.md
  builder/build_env.py
Labels: documentation

#27 Add links to docs.
  README.md
Labels: documentation

#26 Loop create_all_recipes over each variant combination
  builder/build_env.py
  envs/dali-env.yaml
  envs/horovod-env.yaml
  envs/opence-env.yaml
  envs/pytorch-env.yaml
  envs/tensorflow-env.yaml
  envs/xgboost-env.yaml
  tests/build_env_test.py
  tests/configlint.py
  tests/test-env2.yaml
Labels: enhancement

#35 Readme beutification
  README.md
Labels: documentation, enhancement

#31 Cleanup `configlint.py` into integration tool.
  .github/workflows/builder-unit-test.yml
  .pylintrc
  README.md
  builder/utils.py
  ci_common_scripts/imageconfig
  ci_common_scripts/run_build.sh
  doc/README.build_env.md
  open-ce/__init__.py
  open-ce/build_env.py
  open-ce/build_feedstock.py
  open-ce/docker_build.py
  open-ce/utils.py
  open-ce/validate_config.py
  open-ce/validate_env.py
  tests/README.md
  tests/build_env_test.py
  tests/build_feedstock_test.py
  tests/configlint.py
  tests/docker_build_test.py
  tests/helpers.py
  tests/pytest.ini
  tests/util_test.py
  tests/validate_config_test.py
Labels: enhancement

#34 Add cuda_compiler to conda_build_config
  conda_build_config.yaml
  open-ce/docker_build.py
Labels: enhancement
